### ISSUE TITLE
Enhancement - avltree.hpp - at

### ISSUE THREAD

**Issue by ghost** [s-grimm/AvlTree#14]
Warning 1   warning C4172: returning address of local variable or temporary c:\users\travis\documents\github\avltree\avltree\avltree.hpp    309 1   avltree

Gets hit with this compile warning

**Comment by ghost** [comment]
Setting the return type back to Type&:
Error   1   error C2440: 'return' : cannot convert from 'int' to 'int &'    c:\users\travis\documents\github\avltree\avltree\avltree.hpp    309 1   avltree

**Comment by s-grimm** [comment]
Closed as new framework does not duplicate
